{{- if eq .Values.global.deployment.platform "gcp" -}}
apiVersion: monitoring.googleapis.com/v1
kind: ClusterPodMonitoring
metadata:
  name: "{{ include "sync.fullname" . }}"
spec:
  selector:
    {{- include "sync.selectorLabels" . | nindent 4 }}
  endpoints:
    - port: 9464
      interval: 30s
{{- end }}
